language: java
deploy:
  provider: heroku
  on:
    branch: deploy
  api_key:
    secure: Y057Xm4crWYeB4nJRqNwXXjSjx+xxZY2ai0oZ1lLS3xypShGEzTsUhQEkIjUIJQETgjhc21sueUTHrZGHZ0LySZonFO8SAjXW2YzSX8DYU7cLG3/a7/VK678uKIbbeDzhRzTPxUrYPgrYHorDAIYNQPVwggOkrN9KL+2ErDWW3dCmqt2wjKaE18zx4ojNwyLodrOH6TG6aeWMORkWtwu4vqCGECOos/Dp2vPQMU3pr7c1TvkKFXQNP6VTjbImR6ymOsGfn1rZHqxtzMqebwBye4vf2rhse4RNbQjlxMOjX2p1uo0A42uQYwrV8NLJBSP6m+AyxXdHxURNamLNRMhPtR1ypVItVHBJDH7VPv6qmDFuW8d9F9xbova1YKJI7PqJ06TPEA9qdx3Bp2U3UecgFLK5MXxNXnzr9d1WZ8uC1xcSyo1uIFAwDmeuyCbtGPgQg8ZSkTR/NxkFRBvYeyT1Jjnl0eQ4XcdUVbGBxfvm/R0PW9dZjmbVaOb9tE0w9tBB0swqcPKOlgk8kFT51xrNlmme9i0peLv/wTS3NC/yDv4M9KJuB0ZulkqhOtZk+r5Ec7NJ/TcQRcFF986Ah7Ox2q8463pcOz5XRQlKZcaOlBwbJjewaw+61dulthlb0KisMngLlxO5D9YdaXvQw/Stz4HdYcK8W+MU082oO107eo=
app: argus-server
